quarkus:
  datasource:
    db-kind: other
    jdbc:
      driver: org.sqlite.JDBC
      url: jdbc:sqlite:sync_family.db
      max-size: 5
      min-size: 1

  flyway:
    migrate-at-start: true
    locations: db/migration

  jooq:
    dialect: sqlite

  log:
    level: INFO
    category:
      "ru.syncfamily":
        level: DEBUG
      "org.jooq":
        level: WARN

sync-family:
  bot:
    token: ${BOT_TOKEN:YOUR_DEFAULT_TOKEN_HERE}
    name: sync_family_bot

  parser:
    delimiters: ",|\n|;"